### ISSUE TITLE
Animated landing page in portfolio website.

### ISSUE THREAD

**Issue by abhikhedekar4241** [abhikhedekar4241/portfolio-website#1]
Landing page with less content and huge animation. On landing page, only company name and navigation section is more than enough. But, animation is must.

**Comment by infern018** [comment]
can I work on this?

**Comment by abhikhedekar4241** [comment]
If you don't have any doubts, I will assign you immediately.

**Comment by infern018** [comment]
ok sure i'll be starting on this one

**Comment by infern018** [comment]
also, will it be good if i kept the landing page minimalist and aesthetic with animation?

**Comment by abhikhedekar4241** [comment]
Just name of the company with beautiful animation. If you have any idea for navigation section, you can add that too.

**Comment by infern018** [comment]
hey @abhikhedekar4241 , regarding the updated policies of [HacktoberFest 2020](https://hacktoberfest.digitalocean.com/hacktoberfest-update) , can you please add the **hacktoberfest** as topic in this repo...

**Comment by abhikhedekar4241** [comment]
@infern018 Sure. I will.
