### ISSUE TITLE
Dark mode on landing page has no transition

### ISSUE THREAD

**Issue by museHD** [abhikhedekar4241/portfolio-website#22]
It would be easier on the eyes if switching back and forth between dark mode was a gradual change rather than a sudden one. Shouldn't be too hard to implement

**Comment by abhikhedekar4241** [comment]
If you are interested in doing this, I can assign you.

**Comment by museHD** [comment]
> If you are interested in doing this, I can assign you.

Yes please, I've also already made a pull request @ #23
