### ISSUE TITLE
Add dark mode and light mode switch and style accordingly.

### ISSUE THREAD

**Issue by abhikhedekar4241** [abhikhedekar4241/portfolio-website#7]
You need to change colours according to current mode. Light mode and Dark mode switch.

**Comment by kavithamanoharan18** [comment]
Hi @abhikhedekar4241, can I pick this issue?

**Comment by abhikhedekar4241** [comment]
Sure. I will assign you.

**Comment by hackgone** [comment]
can i work on this issue if not assigned ?

**Comment by abhikhedekar4241** [comment]
It is already complete. Join this [Discord Server](https://discord.gg/qDrRSU). We are planning for new project.
